spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./dev_db;MODE=MySQL
    username: dev
    password: dev
  h2.console:
    enabled: true
    path: /h2-console
    settings:
      trace: false
      web-allow-others: false
