server.port: 9901

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aisystem?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: shawn
    password: Shawn441
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  mybatis:
    type-aliases-package: com.xiaomi.user.model
    configuration:
      map-underscore-to-camel-case: true

  druid:
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000

  redis:
    host: localhost
    port: 6379

  cache:
    type: redis

  application:
    name: "user-service"

chatglm:
  api:
    url: "https://open.bigmodel.cn/api/paas/v4/chat/completions"
    key: "021d2e70ada645dfa0e8562344d62ca4.QEmZKAJIk5vM9g4e"


