spring:

  datasource:
    url: jdbc:mysql://localhost:3306/aisystem?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: shawn
    password: Shawn441
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  mybatis:
    type-aliases-package: com.xiaomi.wusheng.work_0303.model

  druid:
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000

